-- BuyfromGAB Supabase database setup
-- Run once in the Supabase SQL Editor for the intended project.
-- Safe to re-run for schema and reference data. Existing product rows are not overwritten.
-- Do not put Supabase service-role keys, passwords, or payment secrets in this file.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create sequence if not exists public.order_number_seq start with 1001;

-- ---------------------------------------------------------------------------
-- Shared helpers and authentication profiles
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_buyfromgab on auth.users;
create trigger on_auth_user_created_buyfromgab
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create table if not exists public.user_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'staff')),
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create or replace function public.has_admin_access()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = (select auth.uid())
      and ur.role in ('admin', 'staff')
  );
$$;

create or replace function public.is_store_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = (select auth.uid())
      and ur.role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

create table if not exists public.categories (
  id text primary key,
  name text not null,
  description text not null default '',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_id_format check (id ~ '^[a-z0-9-]+$')
);

create table if not exists public.subcategories (
  id text primary key,
  category_id text not null references public.categories (id) on delete cascade,
  name text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, category_id),
  constraint subcategories_id_format check (id ~ '^[a-z0-9-]+$')
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id text not null references public.categories (id) on delete restrict,
  subcategory_id text,
  sku text unique,
  slug text not null unique,
  name text not null,
  description text not null default '',
  brand text not null default 'BuyfromGAB',
  price numeric(12,2) not null check (price >= 0),
  compare_at_price numeric(12,2) check (compare_at_price is null or compare_at_price >= price),
  image_url text,
  emoji text not null default '📦',
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  sales_count integer not null default 0 check (sales_count >= 0),
  is_best_seller boolean not null default false,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_subcategory_belongs_to_category
    foreign key (subcategory_id, category_id)
    references public.subcategories (id, category_id)
    on update cascade on delete set null (subcategory_id)
);

create index if not exists products_category_active_idx
  on public.products (category_id, is_active, name);
create index if not exists products_subcategory_idx
  on public.products (subcategory_id);
create index if not exists products_brand_idx
  on public.products (brand);
create index if not exists products_best_seller_idx
  on public.products (is_best_seller) where is_active;

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  image_url text not null,
  alt_text text not null default '',
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Customers, orders, payments, and inventory
-- ---------------------------------------------------------------------------

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users (id) on delete set null,
  full_name text not null,
  email text not null,
  phone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_email_lower_idx on public.customers (lower(email));
create index if not exists customers_created_at_idx on public.customers (created_at desc);

create table if not exists public.shipping_methods (
  id text primary key,
  name text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  estimated_days_min smallint check (estimated_days_min is null or estimated_days_min >= 0),
  estimated_days_max smallint check (estimated_days_max is null or estimated_days_max >= estimated_days_min),
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id text primary key check (id in ('whatsapp', 'paystack', 'hubtel')),
  name text not null,
  description text not null default '',
  is_enabled boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discount_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  minimum_subtotal numeric(12,2) not null default 0 check (minimum_subtotal >= 0),
  max_redemptions integer check (max_redemptions is null or max_redemptions > 0),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  starts_at timestamptz,
  expires_at timestamptz,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint discount_code_format check (code = upper(trim(code))),
  constraint discount_percentage_range check (discount_type <> 'percentage' or discount_value <= 100),
  constraint discount_dates_valid check (expires_at is null or starts_at is null or expires_at > starts_at)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default (
    'BG-' || lpad(nextval('public.order_number_seq')::text, 6, '0')
  ),
  tracking_token uuid not null unique default gen_random_uuid(),
  customer_id uuid not null references public.customers (id) on delete restrict,
  shipping_method_id text references public.shipping_methods (id) on delete set null,
  discount_code_id uuid references public.discount_codes (id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  shipping_address jsonb not null default '{}'::jsonb,
  customer_note text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'paid', 'shipped', 'delivered', 'cancelled')),
  payment_method text not null check (payment_method in ('whatsapp', 'paystack', 'hubtel')),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  total_amount numeric(12,2) not null check (total_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  constraint orders_total_matches_parts check (total_amount = subtotal - discount_amount + shipping_amount)
);

create index if not exists orders_customer_created_idx on public.orders (customer_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders (status, created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id bigint references public.products (id) on delete set null,
  product_name text not null,
  product_sku text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items (order_id);
create index if not exists order_items_product_idx on public.order_items (product_id);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete restrict,
  quantity_change integer not null check (quantity_change <> 0),
  quantity_after integer not null check (quantity_after >= 0),
  reason text not null check (reason in ('order', 'restock', 'correction', 'return')),
  order_id uuid references public.orders (id) on delete set null,
  note text not null default '',
  actor_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_product_idx
  on public.inventory_movements (product_id, created_at desc);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  old_status text,
  new_status text not null,
  actor_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists order_status_history_order_idx
  on public.order_status_history (order_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Customer features, store configuration, and moderation
-- ---------------------------------------------------------------------------

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete set null,
  display_name text not null,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null check (char_length(trim(review_text)) between 10 and 600),
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_reviews_published_idx
  on public.product_reviews (product_id, created_at desc) where is_published;

create table if not exists public.wishlists (
  customer_id uuid not null references public.customers (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (customer_id, product_id)
);

create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null,
  is_public boolean not null default false,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Timestamp, inventory, and order-history triggers
-- ---------------------------------------------------------------------------

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists subcategories_set_updated_at on public.subcategories;
create trigger subcategories_set_updated_at before update on public.subcategories
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists shipping_methods_set_updated_at on public.shipping_methods;
create trigger shipping_methods_set_updated_at before update on public.shipping_methods
for each row execute function public.set_updated_at();

drop trigger if exists payment_methods_set_updated_at on public.payment_methods;
create trigger payment_methods_set_updated_at before update on public.payment_methods
for each row execute function public.set_updated_at();

drop trigger if exists discount_codes_set_updated_at on public.discount_codes;
create trigger discount_codes_set_updated_at before update on public.discount_codes
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists product_reviews_set_updated_at on public.product_reviews;
create trigger product_reviews_set_updated_at before update on public.product_reviews
for each row execute function public.set_updated_at();

drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at before update on public.store_settings
for each row execute function public.set_updated_at();

create or replace function public.record_inventory_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.stock_quantity is distinct from old.stock_quantity then
    insert into public.inventory_movements (
      product_id, quantity_change, quantity_after, reason, order_id, actor_user_id
    ) values (
      new.id,
      new.stock_quantity - old.stock_quantity,
      new.stock_quantity,
      case
        when current_setting('app.inventory_reason', true) = 'order' then 'order'
        when new.stock_quantity > old.stock_quantity then 'restock'
        else 'correction'
      end,
      case
        when current_setting('app.inventory_reason', true) = 'order'
          and current_setting('app.inventory_order_id', true) is not null
        then current_setting('app.inventory_order_id', true)::uuid
        else null
      end,
      auth.uid()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists products_record_inventory_change on public.products;
create trigger products_record_inventory_change
after update of stock_quantity on public.products
for each row execute function public.record_inventory_change();

create or replace function public.record_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status is distinct from old.status then
    insert into public.order_status_history (order_id, old_status, new_status, actor_user_id)
    values (new.id, old.status, new.status, auth.uid());
  end if;

  if new.payment_status = 'paid' and old.payment_status is distinct from 'paid' then
    new.paid_at := coalesce(new.paid_at, now());
  end if;
  if new.status = 'shipped' and old.status is distinct from 'shipped' then
    new.shipped_at := coalesce(new.shipped_at, now());
  end if;
  if new.status = 'delivered' and old.status is distinct from 'delivered' then
    new.delivered_at := coalesce(new.delivered_at, now());
  end if;
  return new;
end;
$$;

drop trigger if exists orders_record_status_change on public.orders;
create trigger orders_record_status_change
before update of status, payment_status on public.orders
for each row execute function public.record_order_status_change();

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.customers enable row level security;
alter table public.shipping_methods enable row level security;
alter table public.payment_methods enable row level security;
alter table public.discount_codes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.order_status_history enable row level security;
alter table public.product_reviews enable row level security;
alter table public.wishlists enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles
for select to authenticated
using (id = (select auth.uid()) or (select public.has_admin_access()));

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin on public.profiles
for update to authenticated
using (id = (select auth.uid()) or (select public.is_store_admin()))
with check (id = (select auth.uid()) or (select public.is_store_admin()));

drop policy if exists user_roles_admin_read on public.user_roles;
create policy user_roles_admin_read on public.user_roles
for select to authenticated using ((select public.is_store_admin()));

drop policy if exists user_roles_admin_manage on public.user_roles;
create policy user_roles_admin_manage on public.user_roles
for all to authenticated
using ((select public.is_store_admin()))
with check ((select public.is_store_admin()));

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories
for select to anon, authenticated using (is_active or (select public.has_admin_access()));

drop policy if exists categories_admin_manage on public.categories;
create policy categories_admin_manage on public.categories
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists subcategories_public_read on public.subcategories;
create policy subcategories_public_read on public.subcategories
for select to anon, authenticated using (
  (is_active and exists (
    select 1 from public.categories c
    where c.id = category_id and c.is_active
  )) or (select public.has_admin_access())
);

drop policy if exists subcategories_admin_manage on public.subcategories;
create policy subcategories_admin_manage on public.subcategories
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
for select to anon, authenticated using (
  (is_active and exists (
    select 1 from public.categories c
    where c.id = category_id and c.is_active
  )) or (select public.has_admin_access())
);

drop policy if exists products_admin_manage on public.products;
create policy products_admin_manage on public.products
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists product_images_public_read on public.product_images;
create policy product_images_public_read on public.product_images
for select to anon, authenticated using (exists (
  select 1 from public.products p where p.id = product_id and p.is_active
));

drop policy if exists product_images_admin_manage on public.product_images;
create policy product_images_admin_manage on public.product_images
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists customers_read_owner_or_admin on public.customers;
create policy customers_read_owner_or_admin on public.customers
for select to authenticated
using (user_id = (select auth.uid()) or (select public.has_admin_access()));

drop policy if exists customers_admin_manage on public.customers;
create policy customers_admin_manage on public.customers
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists shipping_methods_public_read on public.shipping_methods;
create policy shipping_methods_public_read on public.shipping_methods
for select to anon, authenticated using (is_active or (select public.has_admin_access()));

drop policy if exists shipping_methods_admin_manage on public.shipping_methods;
create policy shipping_methods_admin_manage on public.shipping_methods
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists payment_methods_public_read on public.payment_methods;
create policy payment_methods_public_read on public.payment_methods
for select to anon, authenticated using (is_enabled or (select public.has_admin_access()));

drop policy if exists payment_methods_admin_manage on public.payment_methods;
create policy payment_methods_admin_manage on public.payment_methods
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists discount_codes_public_read on public.discount_codes;
create policy discount_codes_public_read on public.discount_codes
for select to anon, authenticated using (
  is_active and (starts_at is null or starts_at <= now())
  and (expires_at is null or expires_at > now())
  and (max_redemptions is null or redemption_count < max_redemptions)
);

drop policy if exists discount_codes_admin_manage on public.discount_codes;
create policy discount_codes_admin_manage on public.discount_codes
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists orders_read_owner_or_admin on public.orders;
create policy orders_read_owner_or_admin on public.orders
for select to authenticated
using (
  (select public.has_admin_access())
  or exists (
    select 1 from public.customers c
    where c.id = customer_id and c.user_id = (select auth.uid())
  )
);

drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders
for update to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists order_items_read_owner_or_admin on public.order_items;
create policy order_items_read_owner_or_admin on public.order_items
for select to authenticated
using (exists (
  select 1 from public.orders o
  where o.id = order_id
    and (
      (select public.has_admin_access())
      or exists (
        select 1 from public.customers c
        where c.id = o.customer_id and c.user_id = (select auth.uid())
      )
    )
));

drop policy if exists order_items_admin_manage on public.order_items;
create policy order_items_admin_manage on public.order_items
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists inventory_movements_admin_read on public.inventory_movements;
create policy inventory_movements_admin_read on public.inventory_movements
for select to authenticated using ((select public.has_admin_access()));

drop policy if exists order_status_history_owner_or_admin_read on public.order_status_history;
create policy order_status_history_owner_or_admin_read on public.order_status_history
for select to authenticated
using (exists (
  select 1 from public.orders o
  where o.id = order_id
    and (
      (select public.has_admin_access())
      or exists (
        select 1 from public.customers c
        where c.id = o.customer_id and c.user_id = (select auth.uid())
      )
    )
));

drop policy if exists product_reviews_public_read on public.product_reviews;
create policy product_reviews_public_read on public.product_reviews
for select to anon, authenticated
using (is_published or (select public.has_admin_access()));

drop policy if exists product_reviews_public_submit on public.product_reviews;
create policy product_reviews_public_submit on public.product_reviews
for insert to anon, authenticated
with check (
  not is_published
  and (customer_id is null or exists (
    select 1 from public.customers c
    where c.id = customer_id and c.user_id = (select auth.uid())
  ))
);

drop policy if exists product_reviews_admin_manage on public.product_reviews;
create policy product_reviews_admin_manage on public.product_reviews
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

drop policy if exists wishlists_owner_manage on public.wishlists;
create policy wishlists_owner_manage on public.wishlists
for all to authenticated
using (exists (
  select 1 from public.customers c
  where c.id = customer_id and c.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.customers c
  where c.id = customer_id and c.user_id = (select auth.uid())
));

drop policy if exists store_settings_public_read on public.store_settings;
create policy store_settings_public_read on public.store_settings
for select to anon, authenticated
using (is_public or (select public.has_admin_access()));

drop policy if exists store_settings_admin_manage on public.store_settings;
create policy store_settings_admin_manage on public.store_settings
for all to authenticated
using ((select public.has_admin_access()))
with check ((select public.has_admin_access()));

-- ---------------------------------------------------------------------------
-- Secure checkout and order lookup RPCs
-- ---------------------------------------------------------------------------

create or replace function public.place_order(
  p_customer jsonb,
  p_items jsonb,
  p_shipping_address jsonb,
  p_shipping_method_id text,
  p_payment_method text default 'whatsapp',
  p_discount_code text default null,
  p_customer_note text default ''
)
returns table (
  order_id uuid,
  order_number text,
  tracking_token uuid,
  subtotal numeric,
  discount_amount numeric,
  shipping_amount numeric,
  total_amount numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer_id uuid;
  v_order_id uuid;
  v_order_number text;
  v_tracking_token uuid;
  v_name text;
  v_email text;
  v_phone text;
  v_subtotal numeric(12,2) := 0;
  v_discount numeric(12,2) := 0;
  v_shipping numeric(12,2);
  v_total numeric(12,2);
  v_shipping_method public.shipping_methods%rowtype;
  v_discount_code public.discount_codes%rowtype;
  v_item record;
  v_product public.products%rowtype;
begin
  if jsonb_typeof(p_customer) is distinct from 'object'
     or jsonb_typeof(p_items) is distinct from 'array'
     or jsonb_array_length(p_items) < 1
     or jsonb_array_length(p_items) > 50
     or jsonb_typeof(p_shipping_address) is distinct from 'object' then
    raise exception 'Invalid checkout details.';
  end if;

  v_name := trim(coalesce(p_customer ->> 'full_name', ''));
  v_email := lower(trim(coalesce(p_customer ->> 'email', '')));
  v_phone := trim(coalesce(p_customer ->> 'phone', ''));

  if v_name is null or char_length(v_name) < 2 or char_length(v_name) > 120
     or v_email is null
     or v_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
     or char_length(v_phone) < 6 or char_length(v_phone) > 40
     or length(trim(p_shipping_address::text)) < 3 then
    raise exception 'Enter a valid name, email, phone number, and shipping address.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_items) as input_item(value)
    where jsonb_typeof(input_item.value) is distinct from 'object'
       or coalesce(input_item.value ->> 'product_id', '') !~ '^[0-9]{1,18}$'
       or case
         when coalesce(input_item.value ->> 'quantity', '') ~ '^[0-9]{1,2}$'
           then (input_item.value ->> 'quantity')::integer < 1
             or (input_item.value ->> 'quantity')::integer > 99
         else true
       end
  ) then
    raise exception 'One or more cart items have invalid product or quantity values.';
  end if;

  select * into v_shipping_method
  from public.shipping_methods sm
  where sm.id = p_shipping_method_id and sm.is_active
  for share;
  if not found then
    raise exception 'The selected shipping method is not available.';
  end if;
  v_shipping := v_shipping_method.price;

  if p_payment_method is null or not exists (
    select 1 from public.payment_methods pm
    where pm.id = p_payment_method and pm.is_enabled
  ) then
    raise exception 'The selected payment method is not available.';
  end if;

  for v_item in
    select (input_item.value ->> 'product_id')::bigint as product_id,
           sum((input_item.value ->> 'quantity')::integer)::integer as quantity
    from jsonb_array_elements(p_items) as input_item(value)
    group by (input_item.value ->> 'product_id')::bigint
    order by product_id
  loop
    select * into v_product
    from public.products p
    where p.id = v_item.product_id and p.is_active
    for update;

    if not found then
      raise exception 'A product in the cart is no longer available.';
    end if;
    if v_product.stock_quantity < v_item.quantity then
      raise exception 'Insufficient inventory for "%".', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_item.quantity);
  end loop;

  if p_discount_code is not null and trim(p_discount_code) <> '' then
    select * into v_discount_code
    from public.discount_codes dc
    where dc.code = upper(trim(p_discount_code))
      and dc.is_active
      and (dc.starts_at is null or dc.starts_at <= now())
      and (dc.expires_at is null or dc.expires_at > now())
      and (dc.max_redemptions is null or dc.redemption_count < dc.max_redemptions)
    for update;

    if not found then
      raise exception 'The discount code is invalid or expired.';
    end if;
    if v_subtotal < v_discount_code.minimum_subtotal then
      raise exception 'The order does not meet the minimum subtotal for this discount.';
    end if;

    if v_discount_code.discount_type = 'percentage' then
      v_discount := round(v_subtotal * v_discount_code.discount_value / 100, 2);
    else
      v_discount := v_discount_code.discount_value;
    end if;
    v_discount := least(v_discount, v_subtotal);
  end if;

  v_total := v_subtotal - v_discount + v_shipping;

  insert into public.customers (user_id, full_name, email, phone)
  values ((select auth.uid()), v_name, v_email, v_phone)
  on conflict (user_id) do update
    set full_name = excluded.full_name,
        email = excluded.email,
        phone = excluded.phone
  returning id into v_customer_id;

  insert into public.orders (
    customer_id, shipping_method_id, discount_code_id,
    customer_name, customer_email, customer_phone, shipping_address, customer_note,
    status, payment_method, payment_status,
    subtotal, discount_amount, shipping_amount, total_amount
  ) values (
    v_customer_id, v_shipping_method.id, v_discount_code.id,
    v_name, v_email, v_phone, p_shipping_address,
    left(coalesce(p_customer_note, ''), 1000),
    'pending', p_payment_method, 'pending',
    v_subtotal, v_discount, v_shipping, v_total
  )
  returning id, orders.order_number, orders.tracking_token
  into v_order_id, v_order_number, v_tracking_token;

  for v_item in
    select (input_item.value ->> 'product_id')::bigint as product_id,
           sum((input_item.value ->> 'quantity')::integer)::integer as quantity
    from jsonb_array_elements(p_items) as input_item(value)
    group by (input_item.value ->> 'product_id')::bigint
    order by product_id
  loop
    select * into v_product from public.products p where p.id = v_item.product_id for update;

    insert into public.order_items (order_id, product_id, product_name, product_sku, quantity, unit_price)
    values (v_order_id, v_product.id, v_product.name, v_product.sku, v_item.quantity, v_product.price);

    perform set_config('app.inventory_reason', 'order', true);
    perform set_config('app.inventory_order_id', v_order_id::text, true);
    update public.products
    set stock_quantity = stock_quantity - v_item.quantity,
        sales_count = sales_count + v_item.quantity
    where id = v_product.id;
  end loop;
  perform set_config('app.inventory_reason', '', true);
  perform set_config('app.inventory_order_id', '', true);

  if v_discount_code.id is not null then
    update public.discount_codes
    set redemption_count = redemption_count + 1
    where id = v_discount_code.id;
  end if;

  return query select v_order_id, v_order_number, v_tracking_token,
                      v_subtotal, v_discount, v_shipping, v_total;
end;
$$;

create or replace function public.track_order(
  p_order_number text,
  p_tracking_token uuid
)
returns table (
  order_number text,
  status text,
  payment_status text,
  created_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select o.order_number, o.status, o.payment_status, o.created_at, o.shipped_at, o.delivered_at
  from public.orders o
  where o.order_number = p_order_number
    and o.tracking_token = p_tracking_token;
$$;

revoke all on function public.place_order(jsonb, jsonb, jsonb, text, text, text, text) from public;
grant execute on function public.place_order(jsonb, jsonb, jsonb, text, text, text, text) to anon, authenticated, service_role;
revoke all on function public.track_order(text, uuid) from public;
grant execute on function public.track_order(text, uuid) to anon, authenticated, service_role;
revoke all on function public.has_admin_access() from public;
grant execute on function public.has_admin_access() to anon, authenticated;
revoke all on function public.is_store_admin() from public;
grant execute on function public.is_store_admin() to authenticated;

-- ---------------------------------------------------------------------------
-- Admin reporting views. These obey the underlying table RLS policies.
-- ---------------------------------------------------------------------------

create or replace view public.admin_dashboard_metrics
with (security_invoker = true)
as
select
  coalesce(o.valid_order_count, 0) as valid_order_count,
  coalesce(o.gross_revenue, 0)::numeric(12,2) as gross_revenue,
  coalesce(i.units_ordered, 0)::bigint as units_ordered,
  coalesce(o.customer_count, 0) as customer_count,
  coalesce(o.open_order_count, 0) as open_order_count
from (
  select
    count(*) filter (where status <> 'cancelled') as valid_order_count,
    sum(total_amount) filter (where status <> 'cancelled') as gross_revenue,
    count(distinct customer_id) filter (where status <> 'cancelled') as customer_count,
    count(*) filter (where status in ('pending', 'processing')) as open_order_count
  from public.orders
) o
cross join (
  select coalesce(sum(oi.quantity), 0)::bigint as units_ordered
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where o.status <> 'cancelled'
) i;

create or replace view public.admin_sales_by_category
with (security_invoker = true)
as
select
  c.id as category_id,
  c.name as category_name,
  count(distinct oi.order_id) filter (where o.status <> 'cancelled') as order_count,
  coalesce(sum(oi.quantity) filter (where o.status <> 'cancelled'), 0)::bigint as units_sold,
  coalesce(sum(oi.line_total) filter (where o.status <> 'cancelled'), 0)::numeric(12,2) as sales_total
from public.categories c
left join public.products p on p.category_id = c.id
left join public.order_items oi on oi.product_id = p.id
left join public.orders o on o.id = oi.order_id
group by c.id, c.name, c.display_order;

create or replace view public.admin_top_products
with (security_invoker = true)
as
select
  p.id as product_id,
  p.name as product_name,
  p.category_id,
  coalesce(sum(oi.quantity) filter (where o.status <> 'cancelled'), 0)::bigint as units_sold,
  coalesce(sum(oi.line_total) filter (where o.status <> 'cancelled'), 0)::numeric(12,2) as sales_total
from public.products p
left join public.order_items oi on oi.product_id = p.id
left join public.orders o on o.id = oi.order_id
group by p.id, p.name, p.category_id;

-- ---------------------------------------------------------------------------
-- Grants for the Supabase API roles. RLS remains the access boundary.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

grant select on public.categories, public.subcategories, public.products,
  public.product_images, public.shipping_methods, public.payment_methods,
  public.store_settings to anon, authenticated;
grant select, insert on public.product_reviews to anon, authenticated;

grant select, insert, update, delete on public.profiles, public.user_roles,
  public.categories, public.subcategories, public.products, public.product_images,
  public.customers, public.shipping_methods, public.payment_methods,
  public.discount_codes, public.orders, public.order_items,
  public.inventory_movements, public.order_status_history,
  public.product_reviews, public.wishlists, public.store_settings
to authenticated;

grant usage, select on sequence public.products_id_seq,
  public.product_images_id_seq, public.order_items_id_seq to authenticated;
grant select on public.admin_dashboard_metrics, public.admin_sales_by_category,
  public.admin_top_products to authenticated;
grant all on public.profiles, public.user_roles, public.categories, public.subcategories,
  public.products, public.product_images, public.customers, public.shipping_methods,
  public.payment_methods, public.discount_codes, public.orders, public.order_items,
  public.inventory_movements, public.order_status_history, public.product_reviews,
  public.wishlists, public.store_settings to service_role;
grant all on public.admin_dashboard_metrics, public.admin_sales_by_category,
  public.admin_top_products to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Direct browser-created orders are intentionally not allowed. Use place_order().
revoke insert, delete on public.orders, public.order_items from anon, authenticated;
revoke update, delete on public.orders from anon;
revoke insert, update, delete on public.customers from anon;
revoke insert, update, delete on public.user_roles from anon, authenticated;
revoke insert, update, delete on public.inventory_movements,
  public.order_status_history from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Reference data matching the current BuyfromGAB storefront catalog
-- ---------------------------------------------------------------------------

insert into public.categories (id, name, description, display_order) values
  ('toys', 'Kids toys', 'Toys, games and creative activities for children.', 1),
  ('tech', 'Electronics', 'Everyday electronics and technology accessories.', 2),
  ('pharm', 'Pharmacy', 'First aid, personal care and pharmacy essentials.', 3),
  ('cloth', 'Clothes', 'Everyday clothing, shoes and accessories.', 4),
  ('beauty', 'Beauty', 'Beauty, fragrance, skin care and hair products.', 5),
  ('home', 'Home & kitchen', 'Useful kitchen, bedroom and home essentials.', 6)
on conflict (id) do nothing;

insert into public.subcategories (id, category_id, name, display_order) values
  ('blocks', 'toys', 'Blocks & puzzles', 1),
  ('soft', 'toys', 'Soft toys', 2),
  ('vehicles', 'toys', 'Vehicles & trains', 3),
  ('art', 'toys', 'Arts & crafts', 4),
  ('audio', 'tech', 'Audio', 1),
  ('phones', 'tech', 'Phones & wearables', 2),
  ('accessories', 'tech', 'Accessories', 3),
  ('vitamins', 'pharm', 'Vitamins', 1),
  ('firstaid', 'pharm', 'First aid', 2),
  ('hygiene', 'pharm', 'Hygiene & protection', 3),
  ('tops', 'cloth', 'Tops & hoodies', 1),
  ('jeans', 'cloth', 'Jeans', 2),
  ('dresses', 'cloth', 'Dresses', 3),
  ('shoes', 'cloth', 'Shoes & caps', 4),
  ('makeup', 'beauty', 'Makeup', 1),
  ('fragrance', 'beauty', 'Fragrance', 2),
  ('skin', 'beauty', 'Skin care', 3),
  ('hair', 'beauty', 'Hair', 4),
  ('kitchen', 'home', 'Kitchen', 1),
  ('bedroom', 'home', 'Bedroom', 2),
  ('lighting', 'home', 'Lighting & storage', 3)
on conflict (id) do nothing;

-- Stock is deliberately zero until real inventory counts are entered by an admin.
-- sales_count starts at zero; demo merchandising numbers/reviews are not imported as real sales.
insert into public.products
  (id, category_id, subcategory_id, slug, name, description, brand, price,
   compare_at_price, emoji, stock_quantity, sales_count, is_best_seller)
values
  (1, 'toys', 'blocks', 'wooden-building-blocks', 'Wooden building blocks', 'A set of smooth, colourful wooden blocks for stacking, sorting and building. Great for imaginative play and for practising balance and coordination.', 'Little Joy', 18.50, null, '🧱', 0, 0, false),
  (2, 'toys', 'soft', 'plush-teddy-bear', 'Plush teddy bear', 'A soft, huggable teddy bear with a plush coat and stitched face. A comforting companion for bedtime, car rides and play dates.', 'Play Pals', 14.00, null, '🧸', 0, 0, true),
  (3, 'toys', 'vehicles', 'remote-control-car', 'Remote control car', 'A fast, easy-to-steer remote control car with a rechargeable battery. Drives on pavement and indoors, with a simple controller that kids can use on their own.', 'Play Pals', 32.00, 40.00, '🏎️', 0, 0, false),
  (4, 'toys', 'blocks', '100-piece-jigsaw-puzzle', '100-piece jigsaw puzzle', 'A 100-piece jigsaw puzzle with a bright picture and thick, sturdy pieces. Works well as a quiet activity for one child or a team effort.', 'Little Joy', 12.00, null, '🧩', 0, 0, false),
  (5, 'toys', 'vehicles', 'wooden-train-set', 'Wooden train set', 'A wooden train set with tracks, carriages and a pull-along engine. Kids can rebuild the layout again and again, which keeps play fresh.', 'Little Joy', 27.50, null, '🚂', 0, 0, false),
  (6, 'toys', 'art', 'kids-art-kit', 'Kids art kit', 'An art kit with crayons, coloured pencils, paints and paper in one box. Everything a young artist needs to start drawing straight away.', 'Play Pals', 16.00, null, '🎨', 0, 0, false),
  (7, 'tech', 'audio', 'wireless-headphones', 'Wireless headphones', 'Over-ear wireless headphones with a padded headband and Bluetooth connection. Made for music, calls and long journeys, with a built-in microphone.', 'Panasonic', 59.00, 75.00, '🎧', 0, 0, true),
  (8, 'tech', 'phones', 'smartwatch', 'Smartwatch', 'A smartwatch that shows the time, notifications and daily step count on a bright touchscreen. Pairs with your phone and tracks your activity.', 'Samsung', 89.00, null, '⌚', 0, 0, false),
  (9, 'tech', 'audio', 'portable-speaker', 'Portable speaker', 'A compact Bluetooth speaker with clear sound for its size. Easy to carry around the house, the yard or the beach.', 'LG', 45.00, 55.00, '🔊', 0, 0, false),
  (10, 'tech', 'accessories', 'power-bank-10000-mah', 'Power bank 10,000 mAh', 'A slim 10,000 mAh power bank that keeps your phone charged on the go. Can recharge most phones more than once on a single charge.', 'Nasco', 25.00, null, '🔋', 0, 0, true),
  (11, 'tech', 'phones', 'android-smartphone', 'Android smartphone', 'An Android smartphone with a large display, a dual camera and all-day battery life. A dependable everyday phone for calls, photos and apps.', 'Samsung', 249.00, 289.00, '📱', 0, 0, false),
  (12, 'tech', 'accessories', 'wireless-keyboard', 'Wireless keyboard', 'A slim wireless keyboard with quiet keys and a USB receiver. Works with laptops, desktops and many tablets.', 'LG', 35.00, null, '⌨️', 0, 0, false),
  (13, 'pharm', 'vitamins', 'vitamin-c-tablets', 'Vitamin C tablets', 'Vitamin C tablets for daily use as part of a balanced diet. Easy to swallow and packed in a resealable tub. Always follow the directions on the pack.', 'Wellcare', 9.50, null, '💊', 0, 0, false),
  (14, 'pharm', 'firstaid', 'first-aid-kit', 'First aid kit', 'A compact first aid kit with plasters, bandages, dressings and antiseptic wipes. Small enough for a car, a bag or a school.', 'Healthy Life', 19.00, 24.00, '🩹', 0, 0, false),
  (15, 'pharm', 'hygiene', 'hand-sanitizer-500-ml', 'Hand sanitizer 500 ml', 'A 500 ml hand sanitizer with a pump top for easy use at home or in the office. Quick-drying and gentle on skin.', 'Wellcare', 4.50, null, '🧴', 0, 0, true),
  (16, 'pharm', 'firstaid', 'digital-thermometer', 'Digital thermometer', 'A digital thermometer with a clear display and a fast reading. Simple to use for the whole family. Speak to a health professional about any health concern.', 'Healthy Life', 12.00, null, '🌡️', 0, 0, false),
  (17, 'pharm', 'hygiene', 'face-masks-50-pack', 'Face masks, 50 pack', 'A pack of 50 lightweight disposable face masks with soft ear loops. Comfortable for everyday use.', 'Wellcare', 6.00, null, '😷', 0, 0, false),
  (18, 'pharm', 'hygiene', 'sunscreen-spf-50', 'Sunscreen SPF 50', 'A broad-spectrum SPF 50 sunscreen for face and body. Light on the skin and easy to spread. Reapply as directed on the label.', 'Healthy Life', 11.00, null, '☀️', 0, 0, false),
  (19, 'cloth', 'tops', 'cotton-t-shirt', 'Cotton t-shirt', 'A soft cotton t-shirt with a relaxed everyday fit. Breathable, easy to wash and simple to pair with almost anything.', 'Urban Wear', 12.00, null, '👕', 0, 0, true),
  (20, 'cloth', 'jeans', 'denim-jeans', 'Denim jeans', 'Classic denim jeans with a comfortable straight fit and a durable weave. A wardrobe staple for any season.', 'Urban Wear', 38.00, 48.00, '👖', 0, 0, false),
  (21, 'cloth', 'dresses', 'summer-dress', 'Summer dress', 'A light summer dress with a flattering shape and a breathable fabric. Comfortable for warm days and easy to dress up or down.', 'Sunday Style', 29.00, null, '👗', 0, 0, false),
  (22, 'cloth', 'shoes', 'running-sneakers', 'Running sneakers', 'Lightweight running sneakers with a cushioned sole and breathable upper. Comfortable for workouts and for daily wear.', 'Urban Wear', 54.00, 65.00, '👟', 0, 0, false),
  (23, 'cloth', 'tops', 'zip-hoodie', 'Zip hoodie', 'A warm zip hoodie with a soft lining and front pockets. Perfect for cool mornings and relaxed weekends.', 'Sunday Style', 34.00, null, '🧥', 0, 0, false),
  (24, 'cloth', 'shoes', 'baseball-cap', 'Baseball cap', 'An adjustable cotton baseball cap with a curved brim. Keeps the sun off and goes with any casual outfit.', 'Sunday Style', 10.00, null, '🧢', 0, 0, false),
  (25, 'beauty', 'makeup', 'matte-lipstick', 'Matte lipstick', 'A creamy matte lipstick with rich colour and a comfortable feel. A single swipe gives full coverage.', 'Glow', 9.00, null, '💄', 0, 0, true),
  (26, 'beauty', 'fragrance', 'perfume-50-ml', 'Perfume 50 ml', 'A 50 ml eau de parfum with a fresh floral scent. Long-lasting and suited to both day and evening.', 'Bloom', 42.00, 55.00, '🌸', 0, 0, false),
  (27, 'beauty', 'skin', 'hydrating-face-cream', 'Hydrating face cream', 'A light, hydrating face cream that sinks in quickly without a greasy feel. Suitable for daily use morning and night.', 'Glow', 15.00, null, '🧴', 0, 0, false),
  (28, 'beauty', 'makeup', 'makeup-brush-set', 'Makeup brush set', 'A set of soft makeup brushes for foundation, powder, blush and eyeshadow. Comes in a handy pouch for travel.', 'Bloom', 18.00, null, '🖌️', 0, 0, false),
  (29, 'beauty', 'makeup', 'nail-polish-duo', 'Nail polish duo', 'Two nail polish shades in a gift-ready pair. Smooth application and a glossy finish.', 'Glow', 7.50, null, '💅', 0, 0, false),
  (30, 'beauty', 'hair', 'hair-dryer', 'Hair dryer', 'A powerful hair dryer with several heat and speed settings. Dries hair quickly and includes a concentrator nozzle for styling.', 'Panasonic', 36.00, null, '💨', 0, 0, false),
  (31, 'home', 'kitchen', 'non-stick-cooking-pot', 'Non-stick cooking pot', 'A non-stick cooking pot with a tight-fitting lid and cool-touch handles. Even heating makes it great for soups, stews and rice.', 'Midea', 28.00, 35.00, '🍲', 0, 0, true),
  (32, 'home', 'kitchen', 'ceramic-mug-set', 'Ceramic mug set', 'A set of ceramic mugs that hold a generous serving of tea or coffee. Dishwasher safe and comfortable to hold.', 'Nasco', 16.00, null, '☕', 0, 0, false),
  (33, 'home', 'lighting', 'table-lamp', 'Table lamp', 'A table lamp with a warm glow and a sturdy base. Adds soft light to a bedside, desk or living room.', 'Panasonic', 22.00, null, '💡', 0, 0, false),
  (34, 'home', 'bedroom', 'cotton-bedsheet-set', 'Cotton bedsheet set', 'A cotton bedsheet set with a fitted sheet, flat sheet and pillowcases. Soft, breathable and easy to wash.', 'Homely', 33.00, null, '🛏️', 0, 0, false),
  (35, 'home', 'kitchen', 'electric-kettle', 'Electric kettle', 'An electric kettle with an automatic switch-off and a wide opening for easy filling. Boils quickly for tea, coffee and noodles.', 'Midea', 24.00, 30.00, '🫖', 0, 0, true),
  (36, 'home', 'lighting', 'storage-baskets-3-pack', 'Storage baskets, 3 pack', 'A pack of 3 woven storage baskets in different sizes. Handy for toys, laundry, towels and shelves.', 'Homely', 14.00, null, '🧺', 0, 0, false)
on conflict (id) do nothing;

select setval(
  'public.products_id_seq',
  greatest(coalesce((select max(id) from public.products), 1), 1),
  exists (select 1 from public.products)
);

insert into public.shipping_methods (id, name, description, price, display_order) values
  ('whatsapp-arranged', 'Arrange on WhatsApp', 'Confirm delivery details and any delivery fee with the store team.', 0, 1)
on conflict (id) do nothing;

insert into public.payment_methods (id, name, description, is_enabled, display_order) values
  ('whatsapp', 'Pay via WhatsApp', 'Confirm order and payment directly with the store team.', true, 1),
  ('paystack', 'Paystack', 'Cards and mobile money. Enable after payment integration is configured.', false, 2),
  ('hubtel', 'Hubtel', 'Mobile money and cards. Enable after payment integration is configured.', false, 3)
on conflict (id) do nothing;

insert into public.store_settings (key, value, is_public) values
  ('store_name', '"BuyfromGAB"'::jsonb, true),
  ('currency', '"GHS"'::jsonb, true),
  ('country', '"Ghana"'::jsonb, true),
  ('support_phone', '"+233 54 535 9058"'::jsonb, true),
  ('support_whatsapp', '"233545359058"'::jsonb, true),
  ('support_email', '"hello@buyfromgab.com"'::jsonb, true)
on conflict (key) do nothing;

commit;

-- Bootstrap the first dashboard administrator only after creating the account
-- in Supabase Authentication. Replace the address with the real admin account.
-- Never use the browser-only demo password as a Supabase password.
--
-- insert into public.user_roles (user_id, role)
-- select id, 'admin'
-- from auth.users
-- where lower(email) = lower('your-admin-email@example.com')
-- on conflict (user_id, role) do nothing;
